export enum CaracteristicaIcao {
    ostoEnquadrado = 1,
    OlhosLocalizados = 2,
    DistanciaOlhos = 3,
    Brilho = 4,
    Nitidez = 5,
    Contraste = 6,
    NivelIntensidade = 7,
    SombroRosto = 8,
    AssimetriaIluminacao = 9,
    DirecaoOlhos = 10,
    Oculos = 11,
    Sorriso = 12,
    BocaFechada = 13,
    RazaoFaceLarguraImagem = 14,
    RazaoFaceAlturaImagem = 15,
    PosicionamentoCabeca = 16,
    OlhosVermelhos = 17,
    UniformidadeFundo = 18
}